version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - celery

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A backend beat --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
