# Generated by Django 5.2 on 2025-05-24 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ResumoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('foi_exportado_pdf', models.BooleanField(default=False)),
                ('texto_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_app.textooriginal')),
            ],
        ),
    ]
