# Generated by Django 5.2 on 2025-07-02 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0003_sessaoestudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tempo_meta', models.IntegerField()),
                ('tempo_realizado', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_app.usuario')),
            ],
        ),
    ]
