# Generated by Django 5.2 on 2025-07-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0004_metaestudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('COMECAR', 'Começar'), ('ANDAMENTO', 'Em andamento'), ('FEITO', 'Feito')], default='COMECAR', max_length=10)),
            ],
        ),
    ]
