# Generated by Django 5.2 on 2025-07-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0005_tarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('COMECAR', 'Começar'), ('ANDAMENTO', 'Em andamento'), ('FEITO', 'Feito')], default='COMECAR', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
